module.exports = [
    {
        funktion:[ "Präsident"],
        name: "Broch",
        vorname: "Pascal",
        strasse: "Riederehubel 7",
        plz: "1736",
        ort: "St. Silvester",
        seit:  "2012",
        privat:  "079 647 95 73",
        geschäft:  "026 305 25 61",
        mail:  "pascal.broch67@gmail.com",
    },
    {
        funktion:[  "Sekretärin"],
        name:  "Neuhaus",
        vorname:  "Melanie",
        strasse:  "Schützenweg 11",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2015",
        privat:  "079 102 92 55",
        mail:  "melanie.neuhaus@sensemail.ch",
    },
    {
        funktion:[  "Kassier"],
        name:  "Neuhaus",
        vorname:  "Etienne",
        strasse:  "Buchenacher 47",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 861 76 80",
        mail:  "etu1998@hotmail.com",
    },
    {
        funktion:[  "Junioren-Trainer"],
        name:  "Staub",
        vorname:  "Kurt",
        strasse:  "Dorfstrasse 14",
        plz:  "1795",
        ort:  "Courlevon",
        seit:  "2018",
        privat:  "079 343 40 6",
        mail:  "kurt.staub47@gmail.com",
    },
    {
        funktion:  ["Vizepräsident", "Gruppe 50 Meter", "Munition"],
        name:  "Fornerod",
        vorname:  "Richard",
        strasse:  "Kreuzweg 24",
        plz:  "1734",
        ort:  "Tentlingen",
        seit:  "2008",
        privat:  "079 263 31 34 ",
        geschäft:  "026 414 95 40 ",
        mail:  "richard.fornerod@bluewin.ch",
    },
    {
        funktion:[  "Gruppe 25 Meter"],
        name:  "Aeby",
        vorname:  "Pascal",
        strasse:  "Fuhra 27",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "????",
        privat:  "078 760 20 03",
        mail:  "aeby.pascal@hotmail.com",
    },
    {
        funktion:[  "Luftpistole"],
        name:  "Rumo",
        vorname:  "Marius",
        strasse:  "Neustadt 1",
        plz:  "1735",
        ort:  "Giffers",
        seit:  "2009",
        privat:  "079 479 44 42",
        geschäft:  "026 418 07 89",
        mail:  "marius.rumo@bluewin.ch",
    },
    {
        funktion:[  "Luftpistole"],
        name:  "Egger",
        vorname:  "Myriam",
        strasse:  "Bapstmatte 17",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 245 53 69",
        mail:  "myriam.kuno@bluewin.ch",
    },
    {
        funktion:[  "Homepage"],
        name:  "Fasel",
        vorname:  "Therese",
        strasse:  "Hubel 125",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 359 07 90",
        geschäft:  "",
        mail:  "fasel-therese@bluewin.ch",
    },
    {
        funktion:[  "Wirtin"],
        name:  "Hayoz",
        vorname:  "Lotty",
        strasse:  "Weizacker 4",
        plz:  "1717",
        ort:  "St. Ursen",
        seit:  "2020",
        privat:  "079 614 98 78",
        mail:  "hayoz.charlotte@gmail.com",
    },
    {
        funktion:[  "Ehrenpräsident"],
        name:  "Zürcher",
        vorname:  "Heinrich",
        strasse:  "Harzerweg 25",
        plz:  "1735",
        ort:  "Giffers",
        seit:  "19??",
        privat:  "079 690 57 34",
        mail:  "henri.zuercher@bluewin.ch",
    }
    
];
