module.exports = [
    {
        funktion:[ "Präsident"],
        name: "Broch",
        vorname: "Pascal",
        strasse: "Riederehubel 7",
        plz: "1736",
        ort: "St. Silvester",
        seit:  "2012",
        privat:  "079 647 95 73",
        geschäft:  "026 305 25 61",
        mailAlias:  "pascal.broch67@gmail.com",
        mail: "praesident" //@ssgt.ch
    },
    {
        funktion:[  "Sekretärin"],
        name:  "Neuhaus",
        vorname:  "Melanie",
        strasse:  "Schützenweg 11",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2015",
        privat:  "079 102 92 55",
        mailAlias:  "melanie.neuhaus@sensemail.ch",
        mail: "sekretariat" //@ssgt.ch
    },
    {
        funktion:[  "Kassier"],
        name:  "Neuhaus",
        vorname:  "Etienne",
        strasse:  "Buchenacher 47",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 861 76 80",
        mailAlias: "etu1998@hotmail.com",
        mail:  "kassier" //@ssgt.ch,
    },
    {
        funktion:[  "Junioren-Trainer"],
        name:  "Waeber",
        vorname: "Beat",
        strasse: "Uf em Bärg 25A",
        plz:  "1734",
        ort:  "Tentlingen",
        seit:  "2021",
        privat:  "079 625 24 78",
        mailAlias:  "waeber.beat@yahoo.de",
        mail: "junioren" //@ssgt.ch
    },
    {
        funktion:  ["Vizepräsident"],
        name:  "Fornerod",
        vorname:  "Richard",
        strasse:  "Kreuzweg 24",
        plz:  "1734",
        ort:  "Tentlingen",
        seit:  "2008",
        privat:  "079 263 31 34 ",
        geschäft:  "026 414 95 40 ",
        mailAlias:  "richard.fornerod@bluewin.ch",
        mail: "vize-praesident" //@ssgt.ch
    },
    {
        funktion:[  "Gruppe 25 Meter"],
        name:  "Aeby",
        vorname:  "Pascal",
        strasse:  "Fuhra 27",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "????",
        privat:  "079 358 12 96",
        mailAlias:  "aeby.pascal@hotmail.com",
        mail: "gruppe-25-meter" //@ssgt.ch
    },
    {
        funktion:  ["Gruppe 50 Meter"],
        name:  "Fornerod",
        vorname:  "Richard",
        strasse:  "Kreuzweg 24",
        plz:  "1734",
        ort:  "Tentlingen",
        seit:  "2008",
        privat:  "079 263 31 34 ",
        geschäft:  "026 414 95 40 ",
        mailAlias:  "richard.fornerod@bluewin.ch",
        mail: "gruppe-50-meter" //@ssgt.ch
    },
    {
        funktion:[  "Luftpistole"],
        name:  "Rumo",
        vorname:  "Marius",
        strasse:  "Neustadt 1",
        plz:  "1735",
        ort:  "Giffers",
        seit:  "2009",
        privat:  "079 479 44 42",
        geschäft:  "026 418 07 89",
        mailAlias:  "marius.rumo@bluewin.ch",
        mail: "lupi" //@ssgt.ch
    },
    {
        funktion:[  "Luftpistole"],
        name:  "Egger",
        vorname:  "Myriam",
        strasse:  "Bapstmatte 17",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 245 53 69",
        mailAlias:  "myriam.kuno@bluewin.ch",
        mail: "lupi" //@ssgt.ch
    },
    {
        funktion:[  "Homepage"],
        name:  "Fasel",
        vorname:  "Therese",
        strasse:  "Hubel 125",
        plz:  "1737",
        ort:  "Plasselb",
        seit:  "2020",
        privat:  "079 359 07 90",
        geschäft:  "",
        mailAlias:  "fasel-therese@bluewin.ch",
        mail: "web" //@ssgt.ch
    },
    {
        funktion:[  "Wirtin"],
        name:  "Hayoz",
        vorname:  "Lotty",
        strasse:  "Weizacker 4",
        plz:  "1717",
        ort:  "St. Ursen",
        seit:  "2020",
        privat:  "079 614 98 78",
        mailAlias:  "hayoz.charlotte@gmail.com",
        mail: "buvette" //@ssgt.ch
    },{
        funktion:  ["Munition"],
        name:  "Fornerod",
        vorname:  "Richard",
        strasse:  "Kreuzweg 24",
        plz:  "1734",
        ort:  "Tentlingen",
        seit:  "2008",
        privat:  "079 263 31 34 ",
        geschäft:  "026 414 95 40 ",
        mailAlias:  "richard.fornerod@bluewin.ch",
        mail: "munition" //@ssgt.ch
    }
    //{
    //    funktion:[  "Ehrenpräsident"],
    //    name:  "Zürcher",
    //    vorname:  "Heinrich",
    //    strasse:  "Harzerweg 25",
    //    plz:  "1735",
    //    ort:  "Giffers",
    //    seit:  "19??",
    //    privat:  "079 690 57 34",
    //    mail:  "henri.zuercher@bluewin.ch",
    //}
    
];
